---
- name: Install dependency packages
  ansible.builtin.apt:
    name:
      - python3-apt
      - python3-debian
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
- name: Create GPG key directory
  ansible.builtin.file:
    path: "{{ mackerel_agent_apt_key_dest | dirname }}"
    state: directory
    mode: "0755"
- name: Download GPG key
  ansible.builtin.get_url:
    url: "{{ mackerel_agent_apt_key_url }}"
    dest: "{{ mackerel_agent_apt_key_download_dest }}"
    mode: "0644"
  register: gpg_key_download_result
- name: Convert GPG key
  ansible.builtin.command:
    cmd: gpg --dearmor -o {{ mackerel_agent_apt_key_dest }} {{ mackerel_agent_apt_key_download_dest }}
  when: gpg_key_download_result is changed
- name: Add repository
  ansible.builtin.deb822_repository:
    name: mackerel
    uris: http://apt.mackerel.io/v2/
    suites: mackerel
    components: contrib
    signed_by: "{{ mackerel_agent_apt_key_dest }}"
    architectures:
      - amd64
      - arm64
    enabled: true
    state: present
  register: apt_repository_result
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  when: apt_repository_result is changed
