---
- name: Set host id
  when:
    - mackerel_agent_host_id is defined
    - mackerel_agent_host_id | length > 0
  notify: restart mackerel-agent
  block:
    - name: Create host id directory
      ansible.builtin.file:
        path: /var/lib/mackerel-agent
        state: directory
        mode: "0755"
    - name: Create/update host id file
      ansible.builtin.template:
        src: id.j2
        dest: /var/lib/mackerel-agent/id
        mode: "0644"
- name: Set api key
  ansible.builtin.lineinfile:
    path: /etc/mackerel-agent/mackerel-agent.conf
    regexp: ^#? *apikey = .+
    line: apikey = "{{ mackerel_agent_api_key }}"
- name: Add extra setting
  ansible.builtin.blockinfile:
    path: /etc/mackerel-agent/mackerel-agent.conf
    block: "{{ mackerel_agent_extra_setting }}"
  notify: restart mackerel-agent
